name: Job Queue WorkFlow

on:
  issues:
    types: ['created']

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output_is_successful: ${{ steps.Build.outputs.test }}
    steps:
      - name: Build
        run: |
          if [ `expr ${{ github.event.issue.number }} % 2` == 0 ]; then
            echo "Even";
          else
            echo "Odd...Failing the build";
            echo_ "Failed"
          fi

  test:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.output_is_successful == 'true'
    steps:
      - name: Test
        run:  echo "Test Done"
      
