name: Issue Comment

on: 
  issues:
    types: [opened]
      
jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Get Event Object
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: Add Comment
        run: |
          gh api \
          --method POST \
          /repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
          -f body='Thanks! We will look into the issue' 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
