name: Issue Comment

on: 
  issues:
    types: [created]
      
jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment
        run: |
          gh api -X POST \
            http://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='
            Thanks!
            We will look into the issue'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organization.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
