name: Learn Job Queue WorkFlow

on:
  issues:
    types: ["opened"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: Build
        run: |
          if [ `expr ${{ github.event.issue.number }} % 2` == 0 ]; then
            echo "Even";
          else
            echo "Odd...Failing the build";
            echo_ "Failed"
          fi

  test:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.result == 'success'
    steps:
      - name: Test
        run: echo "Test Done"
