name: Learn Issue Comment

on:
  issues:
    types: [opened]

jobs:
  add-comment-using-action:
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment
        uses: peter-evans/create-or-update-comment@v2.1.1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/Sanket292001/docker-workflow-check
          reactions: "+1"
  add-comment-using-api:
    runs-on: ubuntu-latest
    steps:
      - name: Get Event Object
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: Add Comment
        run: |
          gh api \
          --method POST \
          /repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
          -f body='Thanks! We will look into the issue'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
