name: Main Branch Merge Validation

on:
  push:
    branches: ['main']
    
jobs:
  api_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Display Directory
        run: tree
