name: Main Branch Merge Validation

on:
  workflow_dispatch:
  push:
    branches: ['main']
    
jobs:
  api_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Node Version
        run: node --version
      - name: Install NodeModules
        run: |
          cd ./webapi
          npm install    
      - name: Test
        run: |
          cd ./webapi
          npm test
  
  publish_docker_image:
    runs-on: ubuntu-latest
    needs: [api_test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Node Version
        run: node --version
      - name: Create Docker Image
        run: ${{ toJson(github.event) }} | jq
    
