name: Main Branch PR Validation

on:
  pull_request:
    branches: ['main']
    
jobs:
  api_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node Modules
        run: |
          cd ./webapi
          npm install
      - name: Test
        run: |
          cd ./webapi
          npm test
  
  codeql_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
      - run: |
          make bootstrap
          make release
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
