name: Pull Request Action

on:
  pull_request:
    branches: [main]
    
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: hello-world
        run: echo "Hello World"
      - name: end
        run: echo_ "DONE"
