name: Pull Request Action

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello"
      - name: working
        run: echo "Working"
      - name: end
        run: echo "DONE"
